# Generated by Django 6.0.3 on 2026-03-30 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=100)),
                ('opponent_name', models.CharField(max_length=100)),
                ('team_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('match_report', models.TextField()),
                ('player_of_match', models.CharField(max_length=100)),
                ('opponent_player_of_match', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
                ('match_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('match_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='match_reports.matchreport')),
            ],
        ),
    ]
