# Generated by Django 6.0.3 on 2026-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='match_type',
            field=models.CharField(choices=[('league', 'League'), ('friendly', 'Friendly'), ('tournament', 'Tournament')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='opponent_player_of_match',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='player_of_match',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
