# Generated by Django 6.0.3 on 2026-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_reports', '0002_alter_matchreport_match_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='match_reports/'),
        ),
    ]
