# Generated by Django 6.0.3 on 2026-05-09 10:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_reports', '0003_matchreport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
